<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{bebf08a9-dfaa-4c8e-987d-6b1ebeeda418}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[RunGRAB();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="97" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>