<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="RunGRAB" Id="{73d75011-4d6e-43ad-a6ea-3904f1e24ffa}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM RunGRAB
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="RunGRAB">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>